backend:
  name: git-gateway
  branch: main
media_folder: public/uploads
public_folder: /uploads
publish_mode: editorial_workflow
locale: ja
collections:
  - name: news
    label: ニュース
    label_singular: 記事
    folder: src/content/news
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: md
    format: frontmatter
    fields:
      - { label: タイトル, name: title, widget: string }
      - { label: 日付, name: date, widget: datetime, date_format: YYYY-MM-DD, time_format: false }
      - { label: 下書き, name: draft, widget: boolean, default: false }
      - { label: 概要, name: excerpt, widget: text, required: false }
      - { label: 本文, name: body, widget: markdown }
